
//---------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------
            
public class NoteDTO 
{                    
    public  System.String  Title { get; set; }
                    
    public  System.String  Description { get; set; }
                    
    public  System.Collections.Generic.List<NoteVersionDTO>  NoteVersions { get; set; }
                    
    public  System.Int32  Id { get; set; }
                    
    public  System.Boolean  IsActive { get; set; }
                    
    public  System.DateTime  DateModified { get; set; }
                    
    public  System.DateTime  DateCreated { get; set; }
                    
    public  System.Guid  UserId { get; set; }
                    
    public  System.Boolean  MarkAsDeleted { get; set; }
}   
             
public class NoteVersionDTO 
{                    
    public  System.Int32  Version { get; set; }
                    
    public  System.String  Name { get; set; }
                    
    public  NotesDomain.Entities.Note  Note { get; set; }
                    
    public  System.Int32  FK_NoteId { get; set; }
                    
    public  System.Int32  Id { get; set; }
                    
    public  System.Boolean  IsActive { get; set; }
                    
    public  System.DateTime  DateModified { get; set; }
                    
    public  System.DateTime  DateCreated { get; set; }
                    
    public  System.Guid  UserId { get; set; }
                    
    public  System.Boolean  MarkAsDeleted { get; set; }
}   
 